### ISSUE TITLE
Написать requirements.txt

### ISSUE THREAD

**Issue by annndruha** [profcomff/dwh-pipelines#19]
С одной стороны в [инструкции](https://github.com/profcomff/.github/wiki/%5Bdev%5D-%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%BC%D0%B8) есть пакеты которые нужны. Но всё-таки requirements.txt это канон. А в инструкции можно и забыть что-то поменять.

**Comment by dyakovri** [comment]
Не очень понятно, что именно ты хочешь в итоге увидеть. Там инструкция по установке ПО, тут папка для подгрузки в это ПО. То есть в этой папке лежат скрипты для внешнего приложения
