### ISSUE TITLE
Использовать библиотеку dwh-definitions

### ISSUE THREAD

**Issue by dyakovri** [profcomff/dwh-pipelines#23]
Подключить библиотеку и использовать ее для создания пайплайнов

**Comment by dyakovri** [comment]
Приостановим это дело на полгодика, пока не Airflow не обновилась SQLAlchemy 2

**Comment by Wudext** [comment]
https://stackoverflow.com/questions/76365797/how-do-i-get-airflow-to-work-with-sqlalchemy-2-0-2-when-it-has-a-1-4-48-version

**Comment by grigoriev-semyon** [comment]
Можно закрывать? @dyakovri @Wudext
